### ISSUE TITLE
access to soutenance pre-étude google docs 

### ISSUE THREAD

**Issue by pamellahani** [2024-2025-ECOM-INFO5-G03/Docs#1]
I currently don't have access to the google docs document : 

 link: https://docs.google.com/document/d/1hRxzeo7u37XMTfEsOa1OAqGgenok6SG5LuzkrX3shPQ/edit#heading=h.s6691x1ddhk2

**Comment by alefebvr** [comment]
Hello,
It seems that this is an issue with links/formatting in the Description du barème document.
The links should have been removed, in fact.
You can ignore them.
    alex

**Comment by donsez** [comment]
Ou avez vous trouver le lien vers ce doument ?

**Comment by alefebvr** [comment]
@donsez les liens sont dans le document Consignes et barême.
Il faudrait les supprimer, je pense.

**Comment by pamellahani** [comment]
> Où avez vous trouver le lien vers ce doument ?
@donsez 

Bonjour, 

Le lien ce trouve dans ce pdf qui est sur la page Moode de ECOM : https://im2ag-moodle.univ-grenoble-alpes.fr/pluginfile.php/50224/mod_resource/content/5/Consignes%20et%20bare%CC%82me.pdf 

page 2
